language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - 2.2.10
  - 2.1.10
  - 1.9.3
  - jruby-9.2.7.0
# https://docs.travis-ci.com/user/languages/ruby/
# https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem uninstall bundler -v '>= 2' || true
  - gem install bundler -v '< 2'
  - gem list | grep bundler
script: bundle exec rspec
